FROM python:3.13-bookworm

RUN apt-get update && apt-get install --no-install-suggests --no-install-recommends --yes pipx

ENV PATH="/root/.local/bin:${PATH}"
ENV PYTHONPATH="${PYTHONPATH}:/app"
ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN pipx install poetry
RUN pipx inject poetry poetry-plugin-bundle

COPY ./poetry.lock ./poetry.lock
COPY ./pyproject.toml ./pyproject.toml
RUN poetry install --no-root

COPY ./vibrana ./vibrana

CMD ["poetry", "run", "python3", "/app/vibrana/backend/threads/coordinatorThread.py"]