# ------------------------------
#     Frontend Build
# ------------------------------
FROM node:20-alpine as build
WORKDIR /app
COPY ./vibrana/frontend/package*.json ./
RUN npm i --silent --force
COPY ./vibrana/frontend .
RUN npm run build


# -------------------------------------------
#     Backend Build
# src: https://stackoverflow.com/a/57886655
# -------------------------------------------
FROM python:3.13-bookworm

RUN apt-get update && apt-get install --no-install-suggests --no-install-recommends --yes pipx

ENV PATH="/root/.local/bin:${PATH}"
ENV PYTHONPATH="${PYTHONPATH}:/app"
ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN pipx install poetry
RUN pipx inject poetry poetry-plugin-bundle

COPY ./poetry.lock ./poetry.lock
COPY ./pyproject.toml ./pyproject.toml
RUN poetry install --no-root
RUN poetry add gunicorn
RUN poetry add eventlet

COPY ./vibrana/backend ./vibrana/backend
COPY ./vibrana/algorithms ./vibrana/algorithms
COPY --from=build /app ./vibrana/frontend

EXPOSE 5000
CMD ["poetry", "run", "gunicorn", "-k", "eventlet", "--timeout", "10000", "-w", "1", "-b", "0.0.0.0:5000", "vibrana.backend.main:app"]
