version: "3.9"

services:
  mongodb_container:
    container_name: vibrana_mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodb_volume:/data/db
    networks:
      - web

  redis_container:
    container_name: vibrana_redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    expose:
      - 6379
    volumes:
      - cache:/data
    networks:
      - web

  backend:
    container_name: vibrana_app
    build: ./
    depends_on:
      - redis_container
      - mongodb_container
    ports:
      - "5001:5001"
    expose:
      - 5001
    volumes:
      - ./data:/app/data
    environment:
      - READ_ONLY=False
      - DOCKER=True
    networks:
      - web

  nginx:
    container_name: vibrana_nginx
    image: nginx:mainline-alpine
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vibrana-nginx.rule=Host(`vibrana.rakuschek.at`)"
      - "traefik.http.routers.vibrana-nginx.entrypoints=web"
      - "traefik.http.routers.vibrana-nginx.middlewares=redirect@file"
      - "traefik.http.routers.vibrana-nginx-secured.rule=Host(`vibrana.rakuschek.at`)"
      - "traefik.http.routers.vibrana-nginx-secured.entrypoints=web-secured"
      - "traefik.http.routers.vibrana-nginx-secured.tls.certresolver=mytlschallenge"
    networks:
      - web


volumes:
  mongodb_volume:
    driver: local
  cache:
    driver: local

networks:
  web:
    external: true
