[tool.poetry]
name = "vibrana"
version = "0.1.0"
description = ""
authors = ["Julian Rakuschek <julian.rakuschek@tugraz.at>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.3"
matplotlib = "^3.9.2"
flask-cors = "^5.0.0"
pymongo = "^4.10.1"
scikit-learn = "^1.5.2"
redis = "^5.1.1"
numpy = "<2"
stumpy = "^1.13.0"
tslearn = "^0.6.3"
pandas = "^2.2.3"
fastparquet = "^2024.5.0"
tqdm = "^4.66.5"
h5py = "^3.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
