version: '3.8'

services:
  nginx:
    container_name: anoscout-presentation
    image: nginx:latest
    volumes:
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-anoscout-presentation.rule=Host(`anoscout.rakuschek.at`)"
      - "traefik.http.routers.nginx-anoscout-presentation.entrypoints=web"
      - "traefik.http.routers.nginx-anoscout-presentation.middlewares=redirect@file"
      - "traefik.http.routers.nginx-anoscout-presentation-secured.rule=Host(`anoscout.rakuschek.at`)"
      - "traefik.http.routers.nginx-anoscout-presentation-secured.entrypoints=web-secured"
      - "traefik.http.routers.nginx-anoscout-presentation-secured.tls.certresolver=mytlschallenge"

networks:
  web:
    external: true